- hosts: versioncontrol
  roles:
    - role: geerlingguy.git
      become: yes
      
- hosts: mysqldev
  roles:
    - role: geerlingguy.mysql
      ignore_errors: yes
      become: yes


- hosts: oracleJDK1
  roles:
    - role: williamyeh.oracle-java
      become: yes
